# This file is automatically generated. Do not edit.

PXEngine.licenseKey('EQ618-LJDLI-B8GN3-QBBU3-8M0JM-QUITT-NJRFC-U10SL-RL43M-SETVQ-0OA4D-5S24R-6SNQH-02OR8-KNK7T-R6', forUser:'i.naoya@gmail.com')

def style(str)
  PXEngine.styleSheetFromSource(str, withOrigin:0)
  PXEngine.applyStylesheets
end
