# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('356d6f74354332874463abf23d7875dc_MjU5MzUzMjAxMy0wOC0xNCAwNDo0ODozMC4yNzA1Njk')
  end)
end
